// <auto-generated />
namespace CAFE.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AfterPluralizingOff : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AfterPluralizingOff));
        
        string IMigrationMetadata.Id
        {
            get { return "201705310910030_AfterPluralizingOff"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
